parameters:
    badger.game.listener.class: Badger\Bundle\GameBundle\EventListener\UnlockBadgeListener
    badger.notifier.slack.class: Badger\Bundle\GameBundle\Notifier\SlackNotifier

services:
    badger.game.listener:
        class: '%badger.game.listener.class%'
        arguments:
            - '@router'
            - '@logger'
            - '@badger.notifier.slack'
        tags:
            - { name: kernel.event_listener, event: game.user_unlocks_badge, method: onUnlockBadge }

    badger.notifier.slack:
        class: '%badger.notifier.slack.class%'
        arguments:
            - '%slack_webhook_url%'
            - '@logger'

    security.access.public_decision_manager: '@security.access.decision_manager'
